log_file_path: "synth_log.csv"
max_ip: "127.0.0.1"
max_send_port: 8000
max_receive_port: 8001
max_randomizations: 10

synth_params:
  - VCO 1 Pitch
  - VCO 1 Shape
  - VCO 2 Pitch
  - VCO 2 Shape
  - Cross Mod
  # - Pitch EG
  - Filter Cutoff
  - Filter Resonance
  # - Filter EG Int
  - Key Track
  # - Velocity
  - Amp EG Attack
  - Amp EG Decay
  - Amp EG Sustain
  - Amp EG Release
  - LFO Rate
  - LFO Intensity
  # - Delay HP Cutoff
  - Delay Time
  - Delay Feedback
  # - Voice Depth
